import re
import sys


def main():
    text = "NS WJHJSY RSTYMX, RFS DZYJIJX MFGJ JSUQTWJI HMFXXNH HNUWJWX STY RJWQJD FX NXZXYWJWFQJ HTWZXWNYNXD GX YWX F KTNSIFSHJ UWTZW YWTZRJSFYD KWJJD HNUMFSLW FSN RJFNSL. BMSJ F XNRUQJ HJFZXW XMNA XN JCYJSJI YT GNLFJWX UWTTJXXJ IFWWTXR UJWFXX RZTWTLJ BTWIX, YMJ WJXZYNLM NSYFXYFWYJ DTUZNHWDUY TK UFWX XJHTZRJ RTWJ WJWFQNR NSJI WJFXJQNWD. YMNX QTSTRJ RJXXFLJ NX XYJSYTSFQD QUNFS SJI IJAWJXJ, HTSYNSNYD XMNWY BTWIX FSI QTSJWFJ JCUWJXXJ, YT MJQU B MNJJRNSK QNAFZXNYD. NY YJFX STY WTNDT DT ITSFR ST ITLFSN-XNUTKNH OEFWT; NSXYJI, NY FNRX YT UWTKNAJ F SJSZYFQ FXRUQJ YMFW XYQQ WJQJHJD YJFWFQJ GZNUXJ. FSIQQNX ZXD FYYRJYU YT WJHTJW YMJ XMNKY GD D TTRYJWFSLJ YMJ RXTZ HTRRTS UFWJX BTWIX JSHWDUYNH MNLM-KTTRJW DNHWFNX RNSL JSYFKJW UWTZXYFYNTS UWTTRJ. JAJ S T TBFLJ, FLLJWJWFYNX MNLSFWNRJSYJ NLJWJX TKTW YMJ JSHWDUYNH YJCY YT WJFYNSJX XYWZWFYNTS TBFWJ FSI UWTAJXZJ YWFHPXJ YMJWF FWN JJFJW YT AJWNA. KT WXYNSIJX UJFD UWUJWWY YT WJHTRJW YMJ XMNKY GD ZSJ YMNXJ YJCY YT KTZWQFWYJ YMJ RTRJW HNUMFSL YT UFWPJSNX LFXXJ FSI UWTZQFXXJ YJFY FWJ JFXJWX YT AJWFWD. KTW XYZJYJI XYJD UWUJWXNLMNSL KTWWJXJ QJ HTRRTS TJDY, HSTQXYYD FSI IJKFWYJ XNQJ RJFID JSHWDUYNH RZYYWNRUJSYJ XYFWPXJ."
    
    text = text.replace(" ", "")
    text = text.replace(".", "")
    text = list(text)


    frequency = {}
    for i in range(0, len(text), 2):
        bigramm = text[i]
        if i+1 != len(text):
            bigramm += text[i+1]

        if bigramm in frequency:
            frequency[bigramm] += 1
        else:
            frequency[bigramm] = 1

    frequency = sorted(frequency.items(), key = lambda x : -x[1])
    for item in frequency:
        print(item)


if __name__ == "__main__":
    main()