// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubmissionsClient is the client API for Submissions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubmissionsClient interface {
	ListWorkSubmissions(ctx context.Context, in *ListWorkSubmissionsRequest, opts ...grpc.CallOption) (*ListWorkSubmissionsResponse, error)
}

type submissionsClient struct {
	cc grpc.ClientConnInterface
}

func NewSubmissionsClient(cc grpc.ClientConnInterface) SubmissionsClient {
	return &submissionsClient{cc}
}

func (c *submissionsClient) ListWorkSubmissions(ctx context.Context, in *ListWorkSubmissionsRequest, opts ...grpc.CallOption) (*ListWorkSubmissionsResponse, error) {
	out := new(ListWorkSubmissionsResponse)
	err := c.cc.Invoke(ctx, "/api.v1.Submissions/ListWorkSubmissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubmissionsServer is the server API for Submissions service.
// All implementations must embed UnimplementedSubmissionsServer
// for forward compatibility
type SubmissionsServer interface {
	ListWorkSubmissions(context.Context, *ListWorkSubmissionsRequest) (*ListWorkSubmissionsResponse, error)
	mustEmbedUnimplementedSubmissionsServer()
}

// UnimplementedSubmissionsServer must be embedded to have forward compatible implementations.
type UnimplementedSubmissionsServer struct {
}

func (UnimplementedSubmissionsServer) ListWorkSubmissions(context.Context, *ListWorkSubmissionsRequest) (*ListWorkSubmissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkSubmissions not implemented")
}
func (UnimplementedSubmissionsServer) mustEmbedUnimplementedSubmissionsServer() {}

// UnsafeSubmissionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubmissionsServer will
// result in compilation errors.
type UnsafeSubmissionsServer interface {
	mustEmbedUnimplementedSubmissionsServer()
}

func RegisterSubmissionsServer(s grpc.ServiceRegistrar, srv SubmissionsServer) {
	s.RegisterService(&Submissions_ServiceDesc, srv)
}

func _Submissions_ListWorkSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkSubmissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionsServer).ListWorkSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.Submissions/ListWorkSubmissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionsServer).ListWorkSubmissions(ctx, req.(*ListWorkSubmissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Submissions_ServiceDesc is the grpc.ServiceDesc for Submissions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Submissions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.Submissions",
	HandlerType: (*SubmissionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWorkSubmissions",
			Handler:    _Submissions_ListWorkSubmissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
